name: CI

on:
  pull_request:
    branches:
      - main
      - develop

# discard previous execution if you commit to a branch that is already running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "0.11.1"
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Run Ruff (Lint)
        run: uv run ruff check .
      - name: Run Ruff (Format)
        run: uv run ruff format --check .
      - name: Run tests
        run: uv run pytest
